---
# Per environment values which override defaults in hmpps-remand-and-sentencing/values.yaml

generic-service:
  ingress:
    host: remand-and-sentencing.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://remand-and-sentencing.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk"
    COURT_REGISTER_API_URL: "https://court-register-api.hmpps.service.justice.gov.uk"
    MANAGE_OFFENCES_API_URL: "https://manage-offences-api.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    COMMON_COMPONENTS_ENABLED: 'false'
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api.hmpps.service.justice.gov.uk"
    DOCUMENT_MANAGEMENT_API_URL: "https://document-api.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    ADJUSTMENTS_UI_URL: "https://adjust-release-dates.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"
    COURT_CASES_RELEASE_DATES_API_URL: "https://court-cases-release-dates-api.hmpps.service.justice.gov.uk"
    RECORD_RECALLS_UI_URL: "https://record-a-recall.hmpps.service.justice.gov.uk"
    FEATURES_VIEW_ONLY_ENABLED: 'false'

generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
